# Tag the HEAD commit on main branch with the given version, zip up the files and publish a release
name: Publish a new version
on: 
  workflow_dispatch:
    inputs:
      version_tag:
        description: Release version, format "1.2.3". Tag will be created as "v1.2.3", but release file will not (to comply with Factorio conventions).
        required: true
jobs:
  release:
    name: Tag, zip and publish release
    runs-on: ubuntu-latest
    steps:
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "v${{github.event.inputs.version_tag}}"
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: "stack-combinator_${{ github.event.inputs.version_tag }}.zip"

