# Tag the HEAD commit on main branch with the given version, zip up the files and publish a release
name: Publish a new version
on: 
  workflow_dispatch:
    inputs:
      commit:
        description: Branch or commit to tag for release.
        required: false
        default: master
      version:
        description: Release version, format "1.2.3". Tag will be created as "v1.2.3", but release file will not (to comply with Factorio conventions).
        required: true
env:
  VERSION_TAG: v${{ github.event.inputs.version }}
  FILENAME: stack-combinator_${{ github.event.inputs.version }}
  ZIPNAME: stack-combinator_${{ github.event.inputs.version }}.zip
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
jobs:
  release:
    name: Tag, zip and publish release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Create sub-folder
        run: shopt -s extglob && mkdir "${{ env.FILENAME }}" && mv !("${{ env.FILENAME}}") "${{ env.FILENAME }}"
      - name: Zip files
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: ${{ env.ZIPNAME }}
          exclusions: "*.git*"
      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ env.VERSION_TAG }}
          omitBody: true
          allowUpdates: true
          tag: ${{ env.VERSION_TAG }}
          commit: ${{ github.event.inputs.commit }}
          artifacts: ${{ env.ZIPNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

