# Tag the HEAD commit on main branch with the given version, zip up the files and publish a release
name: Publish a new version
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Release version, format "1.2.3". Tag will be created as "v1.2.3", but release file will not (to comply with Factorio conventions).
        required: true
env:
  VERSION_TAG: "v${{ github.event.inputs.version }}"
  FILENAME: "stack-combinator_${{ github.event.inputs.version }}.zip"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    name: Tag, zip and publish release
    runs-on: ubuntu-latest
    
    steps:
      - name: Tag latest commit
        uses: richardsimko/update-tag@v1.0.5
        with:
          tag_name: ${{ env.VERSION_TAG }}
      - uses: actions/checkout@master
      - name: Zip files
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: ${{ env.FILENAME }}
          exclusions: "*.git*"
      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ env.VERSION_TAG }}
          omitBody: true
          allowUpdates: true
          tag: ${{ env.VERSION_TAG }}
          artifacts: ${{ env.FILENAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

